; 開発環境向けの PHP 設定
memory_limit = 512M
max_execution_time = 60

upload_max_filesize = 32M
post_max_size = 32M

date.timezone = Asia/Tokyo
expose_php = Off

; 開発中はファイル変更を即座に反映させる
opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
